spring.application.name=kantin-kita

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/kantin_kita
spring.datasource.username=root
spring.datasource.password=Mentari@2727
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=your-256-bit-secret-key-for-kantin-kita-app-change-in-production
app.jwt.expiration-ms=86400000

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.info.title=Kantin Kita API
springdoc.info.version=1.0.0
springdoc.info.description=API documentation for Kantin Kita

# Xendit
xendit.api-key=xnd_public_development_MnBAb2nnaYoO4kkcvjZcs8LVZEzCmvINrZVURtNrdOgnHFLfyjTedb2IAplSQ_D
xendit.callback-token=LNq0RRHTTT92maY8hlUMh75iBHSDjr647sApYlZWsgJYsPcJ
xendit.success-redirect-url=http://localhost:3000/orders/
xendit.failure-redirect-url=http://localhost:3000/orders/

# Server
server.port=8080
