import { StallRestaurant, FilterBadge } from "./types"

export const STALLS_DATABASE: StallRestaurant[] = [
  {
    id: "stall-1",
    name: "Soto & Bakso Mbok Sri",
    cuisine: "Soto Ayam, Bakso Urat, Mie Bakso",
    rating: 4.8,
    reviewsCount: "500+",
    walkTime: 8,
    distance: "50m",
    isOpen: true,
    promos: ["Diskon 20%", "Menu Populer", "Cepat Saji"],
    cheapestItemPrice: 15000,
    isInstant: true,
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=400&q=80",
    block: "Blok A",
  },
  {
    id: "stall-2",
    name: "Ayam Geprek Gahar",
    cuisine: "Ayam Geprek, Ayam Crispy, Ricebowl Pedas",
    rating: 4.7,
    reviewsCount: "380+",
    walkTime: 12,
    distance: "70m",
    isOpen: true,
    promos: ["Diskon 30%", "Voucher Rp 5rb", "Geprek Spesial"],
    cheapestItemPrice: 14000,
    isInstant: false,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=400&q=80",
    block: "Blok B",
  },
  {
    id: "stall-3",
    name: "Kopi & Roti Bakar Kanto",
    cuisine: "Kopi Susu Gula Aren, Toast, Roti Bakar Coklat",
    rating: 4.9,
    reviewsCount: "1.2k+",
    walkTime: 4,
    distance: "15m",
    isOpen: true,
    promos: ["Beli 1 Gratis 1", "Es Kopi Susu Murah", "Cemilan Hemat"],
    cheapestItemPrice: 10000,
    isInstant: true,
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=400&q=80",
    block: "Blok A",
  },
  {
    id: "stall-4",
    name: "Dapur Seafood Selera Rasa",
    cuisine: "Ikan Bakar, Udang Geprek, Cumi Saus Padang",
    rating: 4.6,
    reviewsCount: "120+",
    walkTime: 18,
    distance: "120m",
    isOpen: true,
    promos: ["Diskon Spesial 15%", "Seafood Segar"],
    cheapestItemPrice: 28000,
    isInstant: false,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80",
    block: "Blok B",
  },
  {
    id: "stall-5",
    name: "Mie Ayam Pangsit Pak Dadi",
    cuisine: "Mie Ayam Jamur, Pangsit Rebus, Bakso Kuah",
    rating: 4.9,
    reviewsCount: "240+",
    walkTime: 9,
    distance: "60m",
    isOpen: true,
    promos: ["Diskon 25%", "Pangsit Gratis"],
    cheapestItemPrice: 15000,
    isInstant: true,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80",
    block: "Blok A",
  }
]

export const FILTER_BADGES: FilterBadge[] = [
  { id: "under-30", label: "Di bawah Rp 30rb" },
  { id: "instant", label: "Penyajian Instan (<10 mnt)" },
  { id: "rating-high", label: "Rating 4.8+" }
]
